    std::cout << "           ╔══════════════════════════════╗" << std::endl;
    std::cout << "           ║             MENU             ║" << std::endl;
    std::cout << "           ║          Initialize          ║" << std::endl;
    std::cout << "           ║            Screen            ║" << std::endl;
    std::cout << "           ║        Scheduler-test        ║" << std::endl;
    std::cout << "           ║        Scheduler-stop        ║" << std::endl;
    std::cout << "           ║         Report-util          ║" << std::endl;
    std::cout << "           ║            Clear             ║" << std::endl;
    std::cout << "           ║             Exit             ║" << std::endl;
    std::cout << "           ╚══════════════════════════════╝" << std::endl;